version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  app:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb